name: fishing_hobby_app
description: "Aplikasi hobi memancing untuk Kabupaten Bulukumba - Cuaca, Peta Spot, Sonar & Deteksi Karang."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Maps & Location
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^11.0.0
  permission_handler: ^11.3.0
  
  # HTTP & API
  http: ^1.2.0
  
  # Local Storage
  sqflite: ^2.3.0
  path: ^1.9.0
  shared_preferences: ^2.2.0
  
  # State Management
  flutter_bloc: ^8.1.0
  equatable: ^2.0.0
  
  # UI Utilities
  intl: ^0.19.0
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # Utils
  url_launcher: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/.gitkeep